# Generated by Django 5.0.7 on 2024-07-23 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('logo', models.ImageField(default='images/default.jpg', upload_to='images/')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('deadline', models.DateField()),
                ('description_file', models.FileField(blank=True, null=True, upload_to='uploads')),
                ('link', models.URLField()),
            ],
        ),
    ]
