# Generated by Django 5.0.7 on 2024-07-24 15:06

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobs_created_by_jobs_status_alter_jobs_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
