# Generated by Django 5.0.7 on 2024-07-24 15:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_jobs_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
