# Generated by Django 5.0.7 on 2024-08-08 19:00

import jobs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_jobs_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='logo',
            field=models.ImageField(default='images/default.jpg', upload_to='images/', validators=[jobs.models.validate_image_extension]),
        ),
    ]
